export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RLayout({ children }) {
  return <div className={""}>{children}</div>;
}
