export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RLayout({ children }) {
  return <div className={"h-screen p-4"}>{children}</div>;
}
